<a href="https://colab.research.google.com/github/Theejuth/Theejutha-CS01/blob/main/CS01_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from numpy import random
x = random.randint(100, size = (5,10))
print (np.sort(x))

[[ 0  1 10 10 26 61 71 75 91 98]
 [ 3  3  6 14 15 30 55 72 94 95]
 [ 0  4 20 29 31 32 65 84 89 92]
 [ 5 20 25 31 48 54 57 79 85 99]
 [ 9 32 36 51 55 57 64 73 76 99]]
